project:
  type: website

website:
  title: "STAT 515 Redesign Project"
  navbar:
    left:
      - href: index.qmd
        text: Project
      - href: code.qmd
        text: Code

format:
  html:
    theme: cosmo
    toc: true
